### ISSUE TITLE
컴포넌트 분리작업

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CultureLand-Android#3]
redux 를 도입함에 따라, 컴포넌트를 presenter / container 로 분리하여 

component 폴더
 ㄴ index.js // mapStateToProps , mapDispathToProps, logic 을 작성 ( container ) 
 ㄴ signup_controller.jsx (예시, presentational)  

로 나누어서 작성하고자 하는데 의견부탁드립니다

**Comment by 4whomtbts** [comment]
프로젝트 구조
https://github.com/mattermost/mattermost-webapp

참고 부탁드립니다.

**Comment by 4whomtbts** [comment]
notificiation

**Comment by swimjiy** [comment]
적용해도 괜찮을 것 같습니다~ 작업은 각자 만든 컴포넌트로 진행하면 될까요??

**Comment by 4whomtbts** [comment]
> 적용해도 괜찮을 것 같습니다~ 작업은 각자 만든 컴포넌트로 진행하면 될까요??

네 이 이슈에 대해 개별적으로 브랜치 만들고 올려도 될 것 같습니다!
