### ISSUE TITLE
Redux-Saga Container Component 연결 

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CultureLand-Android#36]
Redux-Saga Container Component 연결

**Comment by 4whomtbts** [comment]
빌드중 에러 발생한 것도 함께 고쳤습니다
CultureLand-Android/screens/NoteList/styles.js

**Comment by swimjiy** [comment]
넵 확인했습니다

**Comment by 4whomtbts** [comment]
Sign Screen 함수컴포넌트에서 클래스 컴포넌트로 수정하겠습니다.
어

**Comment by swimjiy** [comment]
넵!
