### ISSUE TITLE
NoteList 폴더 삭제

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CultureLand-Android#40]
NoteList 를 ListComponent 와 prop 을 이용하여 
diaryListScreen 으로 일원화하여 사용하기로 협의되었음에 따라

NoteList 와 사용 코드를 모두 제거하고
어제 ListComponent 의 내용을 diaryListScreen 에 옮겼으나 
ListComponent 가 삭제되지 않았습니다. 따라서 Listcomponent 도 삭제하려고 합니다.

**Comment by swimjiy** [comment]
넵 확인했습니다.
