### ISSUE TITLE
Navigation 연결

### ISSUE THREAD

**Issue by swimjiy** [Nexters/CultureLand-Android#46]
Navigation 연결 작업 진행하겠습니다.

**Comment by 4whomtbts** [comment]
어느 부분 navigation 연결하실 예정이신가요?

**Comment by swimjiy** [comment]
우선 bottom navigation 구현하고, bottom 네비게이션 순서대로  메인+관련 컴포넌트 -> 문화생활 리스트 + 관련 컴포넌트 -> 마이페이지 + 관련 컴포넌트 이런 식으로 생각 중인데 괜찮으신가요??

**Comment by 4whomtbts** [comment]
> 우선 bottom navigation 구현하고, bottom 네비게이션 순서대로 메인+관련 컴포넌트 -> 문화생활 리스트 + 관련 컴포넌트 -> 마이페이지 + 관련 컴포넌트 이런 식으로 생각 중인데 괜찮으신가요??

일단 SignScreen --- 로그인 성공시 ---> main 스크린으로 넘어가는 플로우가 있어야합니다!
로그인 성공시 넘어갈 navigation 코드만 넣어주시면 로그인 성공하고 해당 코드 호출하겠습니다

**Comment by swimjiy** [comment]
넵 작업 완료되면 말씀드리겠습니다!
